/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    id("io.github.goooler.shadow") version "8.1.5" // Use fork until shadow has updated to Java 21
}

repositories {
    mavenLocal()
    maven("https://repo.papermc.io/repository/maven-public/")
    maven("https://repo.erethon.de/snapshots/")
    maven("https://repo.maven.apache.org/maven2/")
    maven("https://oss.sonatype.org/content/groups/public/")
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.21-R0.1-SNAPSHOT")
    implementation("de.erethon:bedrock:1.4.0") {
        exclude(group = "org.inventivetalent.spiget-update", "bukkit")

    }
}

group = "de.erethon.itemizerxs"
version = "1.3-SNAPSHOT"
description = "ItemizerXS"
java.sourceCompatibility = JavaVersion.VERSION_21

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks {
    jar {
        manifest {
            attributes(
                "paperweight-mappings-namespace" to "mojang"
            )
        }
    }
    shadowJar {
        dependencies {
            include(dependency("de.erethon:bedrock:1.4.0"))
        }
        relocate("de.erethon.bedrock", "de.erethon.itemizerxs.bedrock")
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
