name: ItemizerXS
version: 1.3-SNAPSHOT
main: de.erethon.itemizerxs.ItemizerXS
api-version: 1.18
authors: [Fyreum]
description: Konfiguriere deine Items InGame mit Befehlen
website: https://erethon.de
commands:
  itemizerxs:
    aliases:
      - ii
    description: Main command
